controllers:
    resource: ../src/Controller/
    type: attribute

home:
    path: /home
    controller: \App\Controller\HomeController::index

profil:
    path: /profil
    controller: \App\Controller\UserController::index

annonce:
    path: /annonce/{id}
    controller: \App\Controller\AnnonceController::annonce